// ------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated.
//
//     - To turn off auto-generation set:
//
//         [TeamCity (AutoGenerate = false)]
//
//     - To trigger manual generation invoke:
//
//         nuke --generate-configuration TeamCity --host TeamCity
//
// </auto-generated>
// ------------------------------------------------------------------------------

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.*
import jetbrains.buildServer.configs.kotlin.v2018_1.triggers.*
import jetbrains.buildServer.configs.kotlin.v2018_1.vcs.*

version = "2018.2"

project {
    buildType(GenerateCppHeaders)
    buildType(Clean)
    buildType(CompileNative)
    buildType(CompileHtmlPreviewer)
    buildType(Compile)
    buildType(RunLeakTests)
    buildType(RunDesignerTests)
    buildType(RunRenderTests)
    buildType(RunCoreLibsTests)
    buildType(RunHtmlPreviewerTests)
    buildType(RunTests)
    buildType(CreateIntermediateNugetPackages)
    buildType(CreateNugetPackages)
    buildType(Package)
    buildType(ZipFiles)
    buildType(CiAzureWindows)

    buildTypesOrder = arrayListOf(GenerateCppHeaders, Clean, CompileNative, CompileHtmlPreviewer, Compile, RunLeakTests, RunDesignerTests, RunRenderTests, RunCoreLibsTests, RunHtmlPreviewerTests, RunTests, CreateIntermediateNugetPackages, CreateNugetPackages, Package, ZipFiles, CiAzureWindows)

    params {
        text (
            "env.Configuration",
            label = "Configuration",
            description = "configuration",
            value = "",
            allowEmpty = true,
            display = ParameterDisplay.NORMAL)
        checkbox (
            "env.SkipTests",
            label = "SkipTests",
            description = "skip-tests",
            value = "False",
            checked = "True",
            unchecked = "False",
            display = ParameterDisplay.NORMAL)
        text (
            "env.ForceNugetVersion",
            label = "ForceNugetVersion",
            description = "force-nuget-version",
            value = "",
            allowEmpty = true,
            display = ParameterDisplay.NORMAL)
        checkbox (
            "env.SkipPreviewer",
            label = "SkipPreviewer",
            description = "skip-previewer",
            value = "False",
            checked = "True",
            unchecked = "False",
            display = ParameterDisplay.NORMAL)
        select (
            "env.Verbosity",
            label = "Verbosity",
            description = "Logging verbosity during build execution. Default is 'Normal'.",
            value = "Normal",
            options = listOf("Minimal" to "Minimal", "Normal" to "Normal", "Quiet" to "Quiet", "Verbose" to "Verbose"),
            display = ParameterDisplay.NORMAL)
        param(
            "teamcity.runner.commandline.stdstreams.encoding",
            "UTF-8"
        )
    }
}
object GenerateCppHeaders : BuildType({
    name = "GenerateCppHeaders"
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "GenerateCppHeaders --skip"
        }
    }
})
object Clean : BuildType({
    name = "Clean"
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "Clean --skip"
        }
    }
})
object CompileNative : BuildType({
    name = "CompileNative"
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "CompileNative --skip"
        }
    }
    dependencies {
        snapshot(Clean) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
        snapshot(GenerateCppHeaders) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
object CompileHtmlPreviewer : BuildType({
    name = "CompileHtmlPreviewer"
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "CompileHtmlPreviewer --skip"
        }
    }
    dependencies {
        snapshot(Clean) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
object Compile : BuildType({
    name = "Compile"
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "Compile --skip"
        }
    }
    dependencies {
        snapshot(Clean) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
        snapshot(CompileNative) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
        snapshot(CompileHtmlPreviewer) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
object RunLeakTests : BuildType({
    name = "RunLeakTests"
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "RunLeakTests --skip"
        }
    }
    dependencies {
        snapshot(Compile) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
object RunDesignerTests : BuildType({
    name = "RunDesignerTests"
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "RunDesignerTests --skip"
        }
    }
    dependencies {
        snapshot(Compile) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
object RunRenderTests : BuildType({
    name = "RunRenderTests"
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "RunRenderTests --skip"
        }
    }
    dependencies {
        snapshot(Compile) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
object RunCoreLibsTests : BuildType({
    name = "RunCoreLibsTests"
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "RunCoreLibsTests --skip"
        }
    }
    dependencies {
        snapshot(Compile) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
object RunHtmlPreviewerTests : BuildType({
    name = "RunHtmlPreviewerTests"
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "RunHtmlPreviewerTests --skip"
        }
    }
    dependencies {
        snapshot(CompileHtmlPreviewer) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
object RunTests : BuildType({
    name = "RunTests"
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "RunTests --skip"
        }
    }
    dependencies {
        snapshot(RunCoreLibsTests) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
        snapshot(RunRenderTests) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
        snapshot(RunDesignerTests) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
        snapshot(RunHtmlPreviewerTests) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
        snapshot(RunLeakTests) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
object CreateIntermediateNugetPackages : BuildType({
    name = "CreateIntermediateNugetPackages"
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "CreateIntermediateNugetPackages --skip"
        }
    }
    dependencies {
        snapshot(Compile) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
object CreateNugetPackages : BuildType({
    name = "CreateNugetPackages"
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "CreateNugetPackages --skip"
        }
    }
    dependencies {
        snapshot(CreateIntermediateNugetPackages) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
object Package : BuildType({
    name = "Package"
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "Package --skip"
        }
    }
    dependencies {
        snapshot(RunTests) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
        snapshot(CreateNugetPackages) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
object ZipFiles : BuildType({
    name = "ZipFiles"
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "ZipFiles --skip"
        }
    }
})
object CiAzureWindows : BuildType({
    name = "CiAzureWindows"
    type = Type.DEPLOYMENT
    vcs {
        root(DslContext.settingsRoot)
        cleanCheckout = true
    }
    steps {
        exec {
            path = "build.cmd"
            arguments = "CiAzureWindows --skip"
        }
    }
    dependencies {
        snapshot(Package) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
        snapshot(ZipFiles) {
            onDependencyFailure = FailureAction.FAIL_TO_START
            onDependencyCancel = FailureAction.CANCEL
        }
    }
})
